name: Run Selenium C# Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout do c\u00f3digo
        uses: actions/checkout@v4

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar depend\u00eancias
        run: dotnet restore

      - name: Build do projeto
        run: dotnet build --no-restore

      - name: Rodar testes
        run: dotnet test --no-build --logger "trx;LogFileName=results.trx"
